"""add price_per_kg to Product

Revision ID: afe1bdd0ec25
Revises: eb94fafed7b5
Create Date: 2026-02-22 13:42:32.812054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afe1bdd0ec25'
down_revision = 'eb94fafed7b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_per_kg', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('price_per_kg')

    # ### end Alembic commands ###
